name: nlpbook
channels:
  - conda-forge
  - nodefaults
  - pytorch  
  - fastai
  - huggingface
  - nlpbook
dependencies:
  - nlpbook
  - jupyter
  - nb_conda 
  - awscli
  - pip
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0-py3-none-any.whl
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.0.0/en_core_web_lg-3.0.0-py3-none-any.whl
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.0.0/en_core_web_trf-3.0.0-py3-none-any.whl
