wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655015560
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      4: 3.9.12
      5: 0.12.18
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.005
network:
  desc: null
  value: in->256->64
total_run:
  desc: null
  value: 2000
weight_decay:
  desc: null
  value: 0.05
